from __future__ import annotations

from typing import Any, Dict, List, Protocol, runtime_checkable


@runtime_checkable
class WorkerManagerProtocol(Protocol):
    """Protocol describing the WorkerManager behavior required by the app.

    This protocol is runtime_checkable so tests can assert structural
    conformance using isinstance(..., WorkerManagerProtocol).
    """

    async def start_all(self) -> None: ...

    async def stop_all(self) -> None: ...

    async def start_camera(self, camera_identifier) -> bool: ...

    async def stop_camera(self, camera_identifier) -> bool: ...

    async def restart_camera(self, camera_identifier) -> bool: ...

    def status(self) -> Dict[int, Dict[str, Any]]: ...

    def list_workers(self) -> List[int]: ...

    def get_worker(self, camera_id: int) -> Any: ...

    def health_check(self, camera_id: int | None = None) -> Dict[int, Dict[str, Any]] | Dict[str, Any]: ...

    async def shutdown(self) -> None: ...
